coursefeedback/coursefeedback/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^$', 'feedback.views.home', name='home'),
    url(r'^feedback/', include('feedback.urls', namespace="feedback")),
    url(r'^getmail/', 'feedback.views.getmail', name='getmail'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^instructions/$', 'feedback.views.instruction', name='instruction'),)

coursefeedback/feedback/urls.py
__author__ = 'HIRENDRA'

from django.conf.urls import patterns, url

from feedback import views

urlpatterns = patterns('',
                       url(r'^(?P<key>\w+)/$',views.index, name='index'),
                       url(r'^getmail/$',views.getmail, name='getmail'),
                       url(r'^(?P<prof_pk>\d+)/(?P<stud_roll>\w+)/(?P<sub_pk>\d+)/(?P<key>\w+)/$',views.polls, name='polls'),
                       url(r'^analyse/$',views.analyse, name='analyse'),
                       url(r'^analyse/(?P<prof_pk>\d+)/$',views.courseanalyse, name='courseanalyse'),
                        )

coursefeedback/feedback/models.py
from django.db import models
from datetime import datetime

class Student(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    roll_no = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    branch=models.CharField(max_length=100)
    semester=models.IntegerField(max_length=2)
    student_date=models.DateTimeField(default=datetime.now())
    course_type=models.CharField(max_length=20)
    key = models.CharField(max_length = 25)


    def was_published_recently(self):
        return self.student_date<=datetime.now()
    was_published_recently.admin_order_field = 'student_date'
    #to display an icon other than boolean information
    was_published_recently.boolean = True
    # to display a name to the column
    was_published_recently.short_description = 'Added Recently'

    def __str__(self):
        return self.roll_no

class Subject(models.Model):
    students=models.ManyToManyField(Student)
    subject_code = models.CharField(max_length=20)
    subject_name= models.CharField(max_length=200)
    subject_date = models.DateTimeField(default=datetime.now())


    def was_published_recently(self):
        return self.subject_date<datetime.now()
    was_published_recently.admin_order_field = 'subject_date'
    #to display an icon other than boolean information
    was_published_recently.boolean = True
    # to display a name to the column
    was_published_recently.short_description = 'Added Recently'
    def __str__(self):
        return self.subject_code


class Professor(models.Model):
    prof_name=models.CharField(max_length=100)
    prof_id = models.CharField(max_length=20)
    dept=models.CharField(max_length=4)
    prof_date = models.DateTimeField(default=datetime.now())

    def was_published_recently(self):
        return self.prof_date<=datetime.now()
    was_published_recently.admin_order_field = 'prof_date'
    #to display an icon other than boolean information
    was_published_recently.boolean = True
    # to display a name to the column
    was_published_recently.short_description = 'Added Recently?'

    def __str__(self):
        return self.prof_name

class Course(models.Model):
    subject = models.ForeignKey(Subject)
    professor=models.ForeignKey(Professor)
    prof_date = models.DateTimeField(default=datetime.now())

    def __unicode__(self):
        return u'%s %s' % (self.subject, self.professor)


class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    question_date= models.DateTimeField(default=datetime.now())
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.question_date<=datetime.now()
    was_published_recently.admin_order_field = 'question_date'
    #to display an icon other than boolean information
    was_published_recently.boolean = True
    # to display a name to the column
    was_published_recently.short_description = 'Published Recently?'

class Result(models.Model):
    question = models.ForeignKey(Question)
    course = models.ForeignKey(Course)
    excellent_votes = models.IntegerField(default = 0)
    verygood_votes = models.IntegerField(default = 0)
    good_votes = models.IntegerField(default = 0)
    fair_votes = models.IntegerField(default = 0)
    poor_votes = models.IntegerField(default = 0)
    total_votes = models.IntegerField(default = 0)

    def __unicode__(self):
        return u'%s %s' %(self.course, self.question)

class Done(models.Model):
    course=models.ForeignKey(Course)
    student=models.ForeignKey(Student)
    done=models.IntegerField(max_length=1,default=0)

    def __unicode__(self):
        return u'%s   %s    %s' % (self.student, self.course, self.done)

class Comment(models.Model):
    course= models.ForeignKey(Course)
    comment_1 = models.CharField(max_length=1000, null=True, blank=True)
    comment_2 = models.CharField(max_length=1000, null=True, blank=True)
    comment_3 = models.CharField(max_length=1000, null=True, blank=True)
    comment_4 = models.CharField(max_length=1000, null=True, blank=True)

    def __unicode__(self):
        return u'%s' %(self.course)

coursefeedback/feedback/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Student, Subject, Question, Course, Professor, Result, Done
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import string
import random
from django.conf import settings
from django.core.mail import send_mail


def home(request):
    return render(request, 'feedback/getmail.html')


def index(request,key):
    #user = get_object_or_404(User,first_name=key)
    #user=User.objects.get(first_name=key)
    student = Student.objects.get(key = key)
    done_list = student.done_set.all()
    return render(request, 'feedback/course2.html', {'student': student, 'done_list': done_list, 'key':key})


def polls(request, prof_pk, stud_roll, sub_pk, key):
    #student = get_object_or_404(Student, roll_no=stud_roll)
    #professor = get_object_or_404(Professor,id=prof_pk)
    #subject = get_object_or_404(Subject, id=sub_pk)
    student = Student.objects.get(roll_no = stud_roll)
    professor  = Professor.objects.get(id = prof_pk)
    subject = Subject.objects.get(id = sub_pk)
    #user = get_object_or_404(User, first_name=key)
    #key=user.first_name
    course = Course.objects.filter(subject=subject, professor=professor)
    course = course[0]
    d = student.done_set.all()
    result_list = course.result_set.all()

    for done in d:
        if done.course == course:
            if done.student == student:
                key = done.done
    if not key:
        if request.method == "POST":
            for result in result_list:
                choice = request.POST.get(result.question.question_text)
                if choice == 'excellent':
                    result.excellent_votes += 1
                    result.save()
                elif choice == 'verygood':
                    result.verygood_votes += 1
                    result.save()
                elif choice == 'good':
                    result.good_votes += 1
                    result.save()
                elif choice == 'fair':
                    result.fair_votes += 1
                    result.save()
                elif choice == 'poor':
                    result.poor_votes += 1
                    result.save()

                result.total_votes = (
                        result.excellent_votes + result.verygood_votes + result.good_votes + result.fair_votes + result.poor_votes)
                result.save()

            comment_text1 = request.POST.get("comment_1")
            comment_text2 = request.POST.get("comment_2")
            comment_text3 = request.POST.get("comment_3")
            comment_text4 = request.POST.get("comment_4")
            course.comment_set.create(comment_1=comment_text1,
                                      comment_2=comment_text2,
                                      comment_3=comment_text3,
                                      comment_4=comment_text4, )

            for done in d:
                if done.course == course:
                    if done.student == student:
                        done.done = 1
                        done.save()
            #return HttpResponseRedirect(reverse("/feedback/"+str(user.first_name)+"/"))
            #return HttpResponseRedirect(reverse("{% url 'feedback:index' user.first_name %}"))
            return render(request, 'feedback/submitted.html',{'key':student.key,})
        else:
            return render(request, 'feedback/questions2.html', {'result_list1': result_list[:5],
                                                                    'result_list2': result_list[5:10],
                                                                    'result_list3': result_list[10:14],
                                                                    'result_list4': result_list[14:19],
                                                                    'result_list5': result_list[19:21],
                                                                    'course': course,
                                                                    'professor': professor,
                                                                    'subject': subject,
                                                                    'key':student.key,})
    else:
        return render(request, 'feedback/submitted.html',{'key':student.key,})



@login_required(login_url='/login/')
def analyse(request):
    if request.user.is_authenticated():
        if request.user.is_staff:
            professor_list = Professor.objects.all()
            return render(request, 'feedback/analyse.html', {'professor_list': professor_list})
        else:
            return HttpResponse("Not a valid memeber")
    else:
        return HttpResponse("Please Login First")


@login_required(login_url='/login/')
def courseanalyse(request, prof_pk):
    if request.user.is_authenticated():
        if request.user.is_staff:
            professor = Professor.objects.get(pk=prof_pk)
            course_list = professor.course_set.all()

            return render(request, 'feedback/courseanalyse.html', {'course_list': course_list, 'professor': professor})
        else:
            return HttpResponse("Not a valid memeber")
    else:
        return HttpResponse("Please Login First")


def getmail(request):
    email = request.POST.get('email')
    if not email in [user.username for user in User.objects.all()]:
        return render(request, 'feedback/invalid.html')
    else:
        s = Student.objects.filter(email = email)
        key = s[0].key
        text = "Submit the coursefeedback form by clicking this link: http://10.1.1.239/feedback/"+key+"/ or http://14.139.41.172/feedback/"+key+"/"
        send_mail('Course Feedback Portal', text, settings.EMAIL_HOST_USER, [email], fail_silently=False)
        #return HttpResponse("<b>An email has been sent to your email address.Please Follow the link in the email</b>")
        return render(request, 'feedback/sentmail.html')
def instruction(request):
    return render(request, 'feedback/instructions.html')

coursefeedback/feedback/templates/feedback/analyse.html
<!DOCTYPE html>
{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
{% block body %}
<body>

<div class="wrapper col4">
    <div id="container">
        <h5><b>List of Courses and Instructors</b></h5>
    {% for professor in professor_list %}
        <a href = "{% url 'feedback:courseanalyse' professor.id %}">{{professor.prof_name}}</a><br>
    {% endfor %}
    </div>
    </div>
</body>
{% endblock %}
</html>

coursefeedback/feedback/templates/feedback/course2.html
<!DOCTYPE html>

{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
   {% block title %} <title> STUDENTS'S FEEDBACK ON COURSES EVEN SEMESTER 2014-15</title> {% endblock %}
</head>
{% block nav %}
<div class="wrapper col2">
  <div id="topnav">
   <ul><li><a href="/">Home</a></li><li> &#9658;</li><li><a href="#"></a> Course Dashboard </li><li> &#9658;</li>

       </ul>
      </div>
    </div>
{% endblock %}
<body>
{% block body %}
<div>
<div class="wrapper col4">
  <div id="container">
    <div id="content">
    <ol>

<b>Even though you have logged into the system using your login credentials,
your identity for feedback is kept anonymous.</b><br>
Following are the courses you have undergone during the recently concluded semester. Please give your feedback for all the courses. 
If the course is taught by more than one faculty member, the course will appear multiple times, together with the name of
each of the faculty members. The feedback needs to be given teacher-wise.
<h5><b>Completed Feedback Courses</b></h5>

{% for done in done_list %}
    {% if done.done %}
        <li style="font-size:18px;">
                <b>{{done.course.subject.subject_code}} </b><br>
                {{done.course.subject.subject_name}}<br>
                {{done.course.professor.prof_name}}- Done
                <br>
        </li>
    {% endif %}
{% endfor %}
<h5><b> Pending List of Courses For Feedback</b></h5>
{% for done in done_list %}
        {% if not done.done %}

        <li style="font-size:18px;">
           <b> {{done.course.subject.subject_code}} </b> <br>
            {{done.course.subject.subject_name}}<br>
            <ol><a href = "{% url 'feedback:polls' done.course.professor.id student.roll_no done.course.subject.id key %}">
                {{done.course.professor.prof_name}}</a></ol>
            <br>
        </li>
    {% endif %}
{% endfor %}



</div>
</div>
    </div>
    </div>
{% endblock %} 
</body>

</html>

coursefeedback/feedback/templates/feedback/courseanalyse.html
{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
{% block body %}
<body>
{% for course in course_list %}
<div class="wrapper col4">
  <div id="container">
    <h1>{{course.professor.prof_name}}</h1>
    <h1>{{course.subject.subject_name}}</h1><br>
    {% for result in course.result_set.all %}
        <ol>
           <h3>{{result.question}}</h3><br>
            Excellent % =   {% widthratio result.excellent_votes result.total_votes 1 %}
            Very Good % =   {{result.verygood_votes}}
            Good Votes % =   {{result.good_votes}}
            Fair % =   {{result.fair_votes}}
            Poor % =   {{result.poor_votes}}
        </ol>
    {% endfor %}
    <h1>Comment 1</h1>
    {% for comment in course.comment_set.all %}
        <ol>{{comment.comment_1}}</ol>
    {% endfor %}
    <h1>Comment 2</h1>
    {% for comment in course.comment_set.all %}
        <ol>{{comment.comment_2}}</ol>
    {% endfor %}
    <h1>Comment 3</h1>
    {% for comment in course.comment_set.all %}
        <ol>{{comment.comment_3}}</ol>
    {% endfor %}
    <h1>Comment 4</h1>
    {% for comment in course.comment_set.all %}
        <ol>{{comment.comment_4}}</ol>
    {% endfor %}

{% endfor %}
      </div>
    </div>

</body>
{% endblock %}
</html>

coursefeedback/feedback/templates/feedback/getmail.html
<!DOCTYPE html>

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>WELCOME TO STUDENT'S FEEDBACK ON COURSES</title>
{% load staticfiles %}


<link rel="stylesheet" type="text/css" href="{% static 'feedback/navi.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'feedback/forms.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'feedback/login.css' %}" />
</head>
<body>

<div class="wrapper col0">
  <div id="topbar">
   
   
    <br class="clear" />
  </div>
</div>
<div class="wrapper col1">
  <div id="header">
    <div id="logo">
    <img src="/static/images/IIT_BHU_Logo.jpg" width="250px" style="float:left; padding-right:20px;"/>
      <h1 style="padding-top:5px;"><a href="index.html">STUDENT'S FEEDBACK ON COURSES</a></h1>
      <p>EVEN SEMESTER 2014-15</p>
    </div>
    <div class="fl_right">
      <ul>

        <li class="last"><a href="https://mail.google.com/mail/?view=cm&fs=1&to=student.feedback@itbhu.ac.in&su=Problem while filling Feedback&body=Explain Your Problem Here" target="_blank">Report a problem</a></li>
        <li><a href="/instructions">Instructions</a></li>
      </ul>
      <p>Mail: student.feedback@itbhu.ac.in</p>
    </div>
    <br class="clear" />
  </div>
</div>

<div class="wrapper col4">
  <div id="container">
    <div id="content">
    <div id="login">
   


  <form action="/getmail/" align="center" id="myForm"  onsubmit="return validate_email()" role="form" class="form-inline" method="post">
      {% csrf_token %}

    <p>Please enter your Institute email address and click submit. On submission, a system generated email will be sent
      to your Institute email address with the link for giving your feedback on courses that you have undergone during the recently concluded semester.
  </p>
      <div class="form-group">
          <label  for="email">Email Address: </label>

      <input name="email" type="email" id="email"  class="form-control" placeholder="Enter your Official Email ID" />
          </div>

      <button class="btn btn-submit" type="submit" id="submit_button" style="-webkit-box-shadow:rgba(0,0,0,0.0.1) 0 1px 0 0;
	-moz-box-shadow:rgba(0,0,0,0.0.1) 0 1px 0 0;
	box-shadow:rgba(0,0,0,0.0.1) 0 1px 0 0;
	background-color:#5B74A8;
	border:1px solid #29447E;
	font-family:'Lucida Grande',Tahoma,Verdana,Arial,sans-serif;
	font-size:12px;
	font-weight:700;
	padding:8px 16px;
	height:32px;
	color:#fff;
	margin-left:385px;
	margin-top: 5px;
	border-radius:5px;
	-moz-border-radius:5px;
	-webkit-border-radius:5px"  >Submit <span class="glyphicon glyphicon-ok-sign"></span> </button>

    </form>

{{error}}
</div>
    </div>
    </div>
    </div>

</body>
</html>

coursefeedback/feedback/templates/feedback/home.html
<!DOCTYPE html>
{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
{% block body %}
<body>
<div class="wrapper col4">
  <div id="container">
      <li><h4><a href = "{% url 'login' %}">click here</a>  to Login</h4></li><br>
      <li><h4><a href = "{% url 'register' %}">click here</a>  to Register</h4></li>
</div>
</div>
</body>
{% endblock %}
</html>

coursefeedback/feedback/templates/feedback/instructions.html
<!DOCTYPE html>

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>WELCOME TO STUDENT'S FEEDBACK ON COURSES</title>
{% load staticfiles %}


<link rel="stylesheet" type="text/css" href="{% static 'feedback/navi.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'feedback/forms.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'feedback/login.css' %}" />
</head>
<body>

<div class="wrapper col0">
  <div id="topbar">
   
   
    <br class="clear" />
  </div>
</div>
<div class="wrapper col1">
  <div id="header">
    <div id="logo">
    <img src="/static/images/IIT_BHU_Logo.jpg" width="240px" style="float:left; padding-right:4px;"/>
      <h1 style="padding-top:5px;"><a href="index.html">STUDENT'S FEEDBACK ON COURSES</a></h1>
      <p>EVEN SEMESTER 2014-15</p>
    </div>
    <div class="fl_right">
      <ul>

        <li class="last"><a href="https://mail.google.com/mail/?view=cm&fs=1&to=student.feedback@itbhu.ac.in&su=Problem while filling Feedback&body=Explain Your Problem Here" target="_blank">Report a problem</a></li>
        <li><a href="/instructions">Instructions</a></li>
      </ul>
      <p>Mail: student.feedback@itbhu.ac.in</p>
    </div>
    <br class="clear" />
  </div>
</div>

<div class="wrapper col4">
  <div id="container">
    <div id="content">
    <div id="instruction">
   


  <form align="left" id="myForm"  onsubmit="return validate_email()" role="form" class="form-inline" method="post">
      

    <p>1. Enter your Institute email address and click submit. If @iitbhu.ac.in doesn't work use @itbhu.ac.in.
        <br><br>
        2. On submission, a system generated email will be sent to your Institute email address with the link for giving your feedback on courses that you have undergone during the recently concluded semester.
        <br><br>
        3. Click on the link sent to your gmail, then click on the name of a particular professor from the list of courses on the course dashboard page.
   <br><br>
        4. Fill the checkboxes of questions then click on "Submit Feedback".
        <br><br>
        5. ......and it's Done.
       <br><br>
        <b><i>If you are facing any problem with feedback portal for e.g. unable to receive mail, course is not listed etc. feel free to contact us at student.feedback@itbhu.ac.in
</i></b>
        <br> <br>
        <a href="/" style="font-size:18px;">Return to home page</a>
    </p>
     

    </form>

</div>
    </div>
    </div>
    </div>

</body>
</html>

coursefeedback/feedback/templates/feedback/invalid.html
<!DOCTYPE html>
{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
{% block body %}
<body>
<div class="wrapper col4">
  <div id="container">
      <h6><b>Invalid email address.</b></h6><br>
      <h6><b>Note: Try using '@itbhu.ac.in' or '@iitbhu.ac.in'.</b></h6>


</body>
{% endblock %}
</html>

coursefeedback/feedback/templates/feedback/layout.html
<!DOCTYPE html>

<html>
<head lang="en">
    <meta charset="UTF-8">
    {% load staticfiles %}

<title>Welcome to the Student Feedback on Courses Portal</title>
<link rel="stylesheet" type="text/css" href="{% static 'feedback/navi.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'feedback/forms.css' %}" />
<script type="text/javascript">
        //Stop Form Submission of Enter Key Press
        function stopRKey(evt) {
            var evt = (evt) ? evt : ((event) ? event : null);
            var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
            if ((evt.keyCode == 13) && (node.type == "text")) { return false; }
        }
        document.onkeypress = stopRKey;
    </script>
<link rel="stylesheet" type="text/css" href="{% static 'feedback/layout.css' %}" />
{% block title %} <title></title> {% endblock %}
</head>
<body>
<div class="wrapper col0">
  <div id="topbar">
   
   
    <br class="clear" />
  </div>
</div>
<div class="wrapper col1">
  <div id="header">
    <div id="logo">
    
    <img src="/static/images/IIT_BHU_Logo.jpg" width="240px" style="float:left; padding-right:4px;"/>
      <h1><a href="index.html">STUDENTS' FEEDBACK ON COURSES </a></h1>
      <p>EVEN SEMESTER 2014-15</p>
    </div>
   <div class="fl_right">
      <ul>

        <li class="last"><a href="https://mail.google.com/mail/?view=cm&fs=1&to=student.feedback@itbhu.ac.in&su=Problem while filling Feedback&body=Explain Your Problem Here" target="_blank">Report a problem</a></li>
        <li><a href="/instructions">Instructions</a></li>
      </ul>
      <p>Mail: student.feedback@itbhu.ac.in</p>
    </div>
    <br class="clear" />
  </div>
</div>

{% block nav %}
<div class="wrapper col2">
  <div id="topnav">

  

  </div>
</div>

{% endblock %}{% block body %}  {% endblock %}

</body>
</html>

coursefeedback/feedback/templates/feedback/polls.html
<form action ="" method = "post">
    {% for question in question_list %}
        <ol>
            {{question.question_text}}<br>
            {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
            {% endif %}

            {% csrf_token %}
            {% for choice in question.choice_set.all %}
               <input type = "radio" name = "{{question.question_text}}" value = "{{ choice.id }}" required>{{choice.choice_text}}
            {% endfor %}
        </ol>
    {% endfor %}
    <input type = "submit" value = "vote" />
</form>

coursefeedback/feedback/templates/feedback/questions.html
<form action ="" method = "post">
    {% for result in result_list %}
        <ol>
            {{result.question.question_text}}<br>
            {% csrf_token %}
            <input type = "radio" name = "{{result.question.question_text}}" value = "excellent" required>Excellent
            <input type = "radio" name = "{{result.question.question_text}}" value = "verygood" required>Very Good
            <input type = "radio" name = "{{result.question.question_text}}" value = "good" required>Good
            <input type = "radio" name = "{{result.question.question_text}}" value = "fair" required>Fair
            <input type = "radio" name = "{{result.question.question_text}}" value = "poor" required>Poor
        </ol>
    {% endfor %}
    <input type = "text" name = "comment_1" value = "" required>Comment 1<br>
    <input type = "text" name = "comment_2" value = "" required>Comment 2<br>
    <input type = "text" name = "comment_3" value = "" required>Comment 3<br>
    <input type = "text" name = "comment_4" value = "" required>Comment 4<br>


    <input type = "submit" value = "vote" />
</form>

coursefeedback/feedback/templates/feedback/sentmail.html
<!DOCTYPE html>
{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
{% block body %}
<body>
<div class="wrapper col4">
  <div id="container">
      <h5><b>An email has been sent to your email address. Please follow the link in the email.</b></h5><br>

</body>
{% endblock %}
</html>

coursefeedback/feedback/templates/feedback/submitted.html
<!DOCTYPE html>
{% extends "feedback/layout.html" %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
{% block body %}
<body>
<div class="wrapper col4">
  <div id="container">
      <h1>Form submitted</h1><br>
      <h1><a href = "{% url 'feedback:index' key %}">Next Feedback</a></h1>


</body>
{% endblock %}
</html>